### ISSUE TITLE
Not showing new "Overwatch" option & others

### ISSUE THREAD

**Issue by DarioLazzari** [FranzWarm/AlienCRT_UI#10]
Hello, latest release of the Alien RPG system add some features that not show properly in the CRT skin. Please, check this news:
- Added "Overwatch" checkbox to character and synth sheets which displays a status icon on the token.
- Put Radiation markers back on the Synth sheet.
- An Actor having Radiation damage will now show a status icon on the Token and will roll to see if there is any health damage.
If there is it must be applied manually I did not automate this in case there are any cures to be applied.ù

Thank you so much for the hard and great work!

**Comment by DarioLazzari** [comment]
PS. Also, not showing icons for Starving, Freezing, etc. on token.

**Comment by FranzWarm** [comment]
All should be fixed now!

thank you!
