### ISSUE TITLE
No cool style for emotes in chat log

### ISSUE THREAD

**Issue by cSelbrede** [FranzWarm/AlienCRT_UI#14]
If you type a /me emote message in the chat, you don't see a cool-looking chat log. It's just a colored block in which you cannot even see what was done.

![image](https://user-images.githubusercontent.com/203647/162680830-a3607fbf-d4c3-458c-bcd6-655a0a87d604.png)

Interestingly, it also appears to be a problem with the system itself.

![image](https://user-images.githubusercontent.com/203647/162681022-231973b6-0cd2-45a8-badc-0bad581b1895.png)

I was going to take a stab at fixing this myself, but then I thought you might have some cool ideas for what you wanted it to look like. E. g. color.

**Comment by FranzWarm** [comment]
Closed! Thanks for the help
