### ISSUE TITLE
Can you please add Settings?

### ISSUE THREAD

**Issue by jacksands** [FranzWarm/AlienCRT_UI#17]
I really enjoy your module UI, but after some time screen lines and other effects get me a headache, but the colors, icons, push button effect are amazing!

can you add Settings to turn off screen lines and other screen affects?

I cant say if it is a fx or font, if you can take a look.. pls

Erich

**Comment by FranzWarm** [comment]
hey! are you sure you're not talking about the Wayland module? the only effects that the CRT UI has are some mouse overs. I'm not using scan lines... let me know if I can help you with something else!

**Comment by jacksands** [comment]
Actually, I open the css file on your module, Data\modules\alien-crt-ui\css\alien-crt-ui.css and found the line 447

.alienrpg .window-content::before

and change using custom css module so it became equal to ::after (I just don't know enough to make a better solution)
it looks like this

.alienrpg .window-content::before {
	content: " ";
	display: block;
	position: absolute;
	top: 0;
	left: 0;
	bottom: 0;
	right: 0;
	background: rgba(18, 16, 16, 0.1);
	opacity: 0;
	z-index: 2;
	pointer-events: none;
	/** animation: flicker 0.15s infinite; **/
}


take a look on the pic if you notice the difference on the lines... I think it is embedded on the sheet code only.
![change](https://user-images.githubusercontent.com/7229143/170379939-7d8ed525-6d5c-4e75-86a1-c440615768b5.png)

![447](https://user-images.githubusercontent.com/7229143/170379891-bb6c9e80-be11-4e25-a49e-0094db1533ee.png)

but it is just a suggestion,  I really enjoy your UI, I comment also because some people asked me how I made the change, so perhaps it is a good option!
But anyway tks for answering my post!

Erich

**Comment by FranzWarm** [comment]
module discontinued
