### ISSUE TITLE
[0.8.6] Update check prompts for URL change and updates to same version

### ISSUE THREAD

**Issue by r-valyar** [FranzWarm/AlienCRT_UI#4]
In Foundry 0.8.6 when I check for update, the module generates URL change prompt and afterwards updates itself to the same version:

![image](https://user-images.githubusercontent.com/63558984/120276339-3ba0d100-c2bb-11eb-9055-cbd784888b73.png)

![image](https://user-images.githubusercontent.com/63558984/120276313-33489600-c2bb-11eb-9c9b-ba9cc856a267.png)

**Comment by FranzWarm** [comment]
The issue has now been fixed!

Thank you for bringing it to my attention
